name: PHP Stan

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    # Setup ubuntu latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: "PHPStan Badaso Sitemap Module"

    steps:
      - uses: actions/checkout@master

    # Run composer badaso sitemap-module
      - name: Composer update
        run: composer update --no-interaction

    # Badaso SitemapModule Test PHPStan
      - name: Badaso SitemapModule test PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon.dist

